# Generated by Django 4.1.2 on 2022-11-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_alter_food_ingredient_options_alter_food_log_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended_levels',
            name='rec_phos_mg',
        ),
        migrations.RemoveField(
            model_name='recommended_levels',
            name='rec_potassium_mg',
        ),
        migrations.RemoveField(
            model_name='recommended_levels',
            name='rec_protien_g',
        ),
        migrations.RemoveField(
            model_name='recommended_levels',
            name='rec_sodium_mg',
        ),
        migrations.RemoveField(
            model_name='recommended_levels',
            name='rec_water_L',
        ),
        migrations.AddField(
            model_name='food_log',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='trackerapp.user'),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_phos_mg_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_phos_mg_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_potassium_mg_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_potassium_mg_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_sodium_mg_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_sodium_mg_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_water_L_by_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_water_L_female',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recommended_levels',
            name='rec_water_L_male',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
