# Generated by Django 4.1.2 on 2022-11-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_remove_recommended_levels_rec_phos_mg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_log',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='trackerapp.user'),
        ),
    ]
