# Generated by Django 4.1.2 on 2022-11-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0004_alter_food_log_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommended_levels',
            old_name='rec_water_L_by_kg',
            new_name='rec_protein_g_by_kg',
        ),
    ]
