# Generated by Django 4.1.2 on 2022-11-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0006_alter_food_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
