# Generated by Django 4.1.2 on 2022-12-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
